### ISSUE TITLE
v-zoom component doesn't update the zoom image correctly if `img` prop changes

### ISSUE THREAD

**Issue by karthikvt26** [disitec/vue-zoom#2]
Hi,

I am using vZoom as follows

```
<v-zoom :img="selectedImgSrc" :url="selectedImgSrc" width="300"></v-zoom>
```

When the ```selectedImgSrc``` prop changes, the actual ``img`` changes correctly but not its ```zoomImg``` src. 

Am I doing anything wrong?

**Comment by disitec** [comment]
fixed in #4
